apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sample-app-label
                topologyKey: kubernetes.io/hostname