---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  template:
    spec:
      containers:
      - name: sample-app-container
        terminationMessagePolicy: FallbackToLogsOnError
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - 'sleep 120'