---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  selector:
    matchLabels:
      app: sample-app-label
  template:
    metadata:
      labels:
        app: sample-app-label
    spec:
      containers:
      - name: sample-app-container
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
